name: Publish Diva Term to Maven Central

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build with Gradle
      run: ./gradlew build

    - name: Publish Diva Blood
      run: ./gradlew :diva-blood:jreleaserConfig && ./gradlew :diva-blood:publish && ./gradlew :diva-blood:jreleaserFullRelease --stacktrace
      env:
        JRELEASER_GITHUB_TOKEN: "${{ secrets.JRELEASER_GITHUB_TOKEN }}"
        JRELEASER_MAVENCENTRAL_SONATYPE_USERNAME: "${{ secrets.JRELEASER_MAVENCENTRAL_SONATYPE_USERNAME }}"
        JRELEASER_MAVENCENTRAL_SONATYPE_TOKEN: "${{ secrets.JRELEASER_MAVENCENTRAL_SONATYPE_TOKEN }}"
        JRELEASER_GPG_PUBLIC_KEY: "${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}"
        JRELEASER_GPG_SECRET_KEY: "${{ secrets.JRELEASER_GPG_SECRET_KEY }}"
        JRELEASER_GPG_PASSPHRASE: "${{ secrets.JRELEASER_GPG_PASSPHRASE }}"